"""
jira_create_tool.py
===================
Creates a new Jira Story/Issue from generated Gherkin content.

What it does:
  1. Parses the Gherkin text to extract Feature name → Jira Summary
  2. Wraps full Gherkin in Jira wiki markup {code:gherkin} → Description
  3. Auto-detects labels from content keywords
  4. Appends Acceptance Criteria as a separate description section
  5. POSTs the issue via the Atlassian Python API
  6. Returns issue key, URL, and success flag

Config (from .env):
  JIRA_URL, JIRA_USERNAME, JIRA_API_TOKEN  — connection credentials
  JIRA_PROJECT_KEY                          — project to create issues in

Usage:
    from app.tools.jira_create_tool import create_jira_issue_from_gherkin

    result = create_jira_issue_from_gherkin(
        gherkin_text="Feature: OAuth2 SSO\n...",
        user_input="Customer should log in via company SSO"
    )
    if result["success"]:
        print(result["issue_key"])   # e.g. "PROJ-148"
        print(result["issue_url"])
"""

import re
from typing import List, Optional

from atlassian import Jira
from langchain_core.documents import Document

import config
from app.utils.logger import get_logger

logger = get_logger(__name__)


# ── Parsing helpers ───────────────────────────────────────────────────────────

def _extract_feature_name(gherkin_text: str) -> str:
    match = re.search(r"Feature:\s*(.+)", gherkin_text, re.IGNORECASE)
    if match:
        return match.group(1).strip()[:200]
    for line in gherkin_text.splitlines():
        line = line.strip()
        if line:
            return line[:200]
    return "New Feature (auto-generated)"


def _extract_acceptance_criteria(gherkin_text: str) -> str:
    match = re.search(
        r"Acceptance Criteria[:\s]*(.*?)(?=\nOut of Scope|\nTest Generation|\nJIRA|\Z)",
        gherkin_text, re.IGNORECASE | re.DOTALL
    )
    return match.group(1).strip() if match else ""


def _extract_labels(gherkin_text: str, user_input: str) -> List[str]:
    combined = (gherkin_text + " " + user_input).lower()
    label_map = {
        "auth":         ["login","oauth","sso","jwt","token","2fa","mfa","password"],
        "payment":      ["payment","billing","invoice","stripe","checkout"],
        "notification": ["email","notification","alert","sms","webhook"],
        "api":          ["api","rest","endpoint","http","graphql"],
        "security":     ["security","pci","gdpr","encryption","audit"],
        "performance":  ["performance","latency","cache","redis","throughput"],
        "frontend":     ["ui","frontend","react","angular","vue","browser"],
        "backend":      ["backend","service","microservice","spring","java"],
        "database":     ["database","sql","postgres","mysql","migration"],
    }
    return [label for label, kws in label_map.items()
            if any(kw in combined for kw in kws)][:5]


def _build_description(gherkin_text: str, user_input: str) -> str:
    acceptance = _extract_acceptance_criteria(gherkin_text)
    desc = (
        "h3. Original Requirement\n\n"
        f"{user_input}\n\n"
        "----\n\n"
        "h3. Gherkin Specification\n\n"
        "{code:gherkin}\n"
        f"{gherkin_text.strip()}\n"
        "{code}\n"
    )
    if acceptance:
        desc += f"\n----\n\nh3. Acceptance Criteria\n\n{acceptance}\n"
    desc += "\n----\n\n_Auto-generated by LangGraph Enterprise RAG Agent_\n"
    return desc


# ── Main function ─────────────────────────────────────────────────────────────

def create_jira_issue_from_gherkin(
    gherkin_text:  str,
    user_input:    str,
    issue_type:    str = "Story",
    priority:      str = "Medium",
    extra_labels:  Optional[List[str]] = None,
) -> dict:
    """
    Create a new Jira issue from generated Gherkin content.

    Returns:
        dict: {success, issue_key, issue_url, summary, error}
    """
    if not config.JIRA_URL or not config.JIRA_API_TOKEN:
        return _fail("Jira credentials not configured in .env")

    if not getattr(config, "JIRA_PROJECT_KEY", ""):
        return _fail("JIRA_PROJECT_KEY not set in .env")

    logger.info(f"Creating Jira {issue_type} in project: {config.JIRA_PROJECT_KEY}")

    try:
        jira = Jira(
            url=config.JIRA_URL,
            username=config.JIRA_USERNAME,
            password=config.JIRA_API_TOKEN,
            cloud=True
        )

        summary     = _extract_feature_name(gherkin_text)
        description = _build_description(gherkin_text, user_input)
        labels      = list(set(_extract_labels(gherkin_text, user_input)
                               + (extra_labels or [])))

        logger.info(f"  Summary: {summary[:80]}")
        logger.info(f"  Labels : {labels}")

        fields = {
            "project":     {"key": config.JIRA_PROJECT_KEY},
            "summary":     summary,
            "description": description,
            "issuetype":   {"name": issue_type},
            "priority":    {"name": priority},
            "labels":      labels,
        }

        new_issue = jira.create_issue(fields=fields)
        issue_key = new_issue.get("key", "")
        issue_url = f"{config.JIRA_URL}/browse/{issue_key}"

        logger.info(f"Jira issue created: {issue_key}")
        return {
            "success":   True,
            "issue_key": issue_key,
            "issue_url": issue_url,
            "summary":   summary,
            "error":     None,
        }

    except Exception as e:
        logger.error(f"Failed to create Jira issue: {e}")
        return _fail(str(e))


def _fail(reason: str) -> dict:
    logger.warning(f"Jira issue creation skipped: {reason}")
    return {"success": False, "issue_key": None,
            "issue_url": None, "summary": None, "error": reason}
